[build]
  command = "npm install"
  directory = "."
  engines = { node = "18.16.0" }  # Укажи нужную версию Node.js

[run]
  command = "node index.js"  # Убедись, что у тебя файл с именем index.js
  port = 3000

[env]
  TELEGRAM_BOT_TOKEN = "<YOUR_TELEGRAM_BOT_TOKEN>"
  CHAT_ID = "<YOUR_CHAT_ID>"
